### ISSUE TITLE
Rofi menu doesn't look like in the screenshots

### ISSUE THREAD

**Issue by obaranek** [Murzchnvok/rofi-collection#1]
I am running i3 and have this line 
bindsym $mod+d exec rofi -show drun -theme $HOME/.local/share/rofi/themes/dracula/dracula.rasi

however rofi has the right colors but the formatting of the menu is off. 
I get the name of program and then a lot of whitespace and then the icons and then a lot of whitespace

**Comment by Murzchnvok** [comment]
Remove line 5 (drun-display-format: "{icon} {name}";) and see what happens.

**Comment by obaranek** [comment]
still looks the same

**Comment by obaranek** [comment]
![image](https://user-images.githubusercontent.com/59672562/98575222-e94c8400-2286-11eb-87a4-a27f9880ae8a.jpg)

This is how it looks

**Comment by Murzchnvok** [comment]
If you have the fonts and icon pack installed I don't know what's really happening.

**Comment by Murzchnvok** [comment]
It's working fine here.

**Comment by obaranek** [comment]
I do have the fonts and I icons installed but I’m not using them, is that fine?

**Comment by Murzchnvok** [comment]
Oh I see, then make a change to see if it'll solve it:

from

```bash
show-icons: true;
```

to

```bash
show-icons: false;
```

**Comment by obaranek** [comment]
The icons went away but still menu area is too big
![image](https://user-images.githubusercontent.com/59672562/98577317-c53e7200-2289-11eb-9320-81d900e2ce9f.jpg)

**Comment by Murzchnvok** [comment]
Run this in the cli:

```bash
rofi -show drun -width 500
```

**Comment by Murzchnvok** [comment]
Just change the value 500 to the size you want.

**Comment by obaranek** [comment]
That solved the size issue, I’ll try solving the icons issue

**Comment by Murzchnvok** [comment]
Ok.

**Comment by obaranek** [comment]
Thanks, that worked for me!
