### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by flamendless** [Murzchnvok/rofi-collection#3]
Icons are broken.

In nord, the icons are in the center but are too small.
In others, they are in the left but are too small as well.

`fc-list | grep JetBrainsMono` properly shows jebrainsmono fonts.
I also have `papirus-icon-theme` from `sudo pacman -S papirus-icon-theme`

**Comment by Murzchnvok** [comment]
Take a look https://github.com/Murzchnvok/rofi-collection/pull/2

**Comment by flamendless** [comment]
Thanks! Though it still looks not like in the screenshots.

for `murz` theme the icon shows properly in the left but theres a weird broken icon (rectangles) before the name.

**Comment by Murzchnvok** [comment]
I see, I'm not going to change anything because it's just like the screenshots here. And that's really bad, because you're not the first one to have this problem. Thanks!
