### ISSUE TITLE
Themes are missing metadata header

### ISSUE THREAD

**Issue by pabloariasal** [Murzchnvok/rofi-collection#5]
Themes are missing  a description header that, among other things, can serve to show the author in `rofi-theme-selector` when setting the `User` attribute, for example:

https://github.com/davatorium/rofi-themes/blob/master/User%20Themes/material.rasi

will show:

> Material by Tomaszal

in `rofi-theme-selector`

**Comment by Murzchnvok** [comment]
Sure, that sounds good! Sorry for the late response.
